export const acordesGuitarra = {
	"A": { fingers: [[4, 2], [3, 2], [2, 2]], barres: [] },
	"Am": { fingers: [[4, 2], [3, 2], [2, 1]], barres: [] },
	"A7": { fingers: [[4, 2], [2, 2]], barres: [] },
	"Am7": { fingers: [[4, 2], [2, 1]], barres: [] },
	"Amaj7": { fingers: [[4, 2], [3, 1], [2, 2]], barres: [] },
	"Asus2": { fingers: [[4, 2], [3, 2]], barres: [] },
	"Asus4": { fingers: [[4, 2], [3, 2], [2, 3]], barres: [] },
	"A6": { fingers: [[4, 2], [3, 2], [2, 2], [1, 2]], barres: [] },
	"Am6": { fingers: [[4, 2], [3, 2], [2, 1], [1, 2]], barres: [] },
	"A#": { fingers: [[4, 3], [3, 3], [2, 3]], barres: [{ fromString: 5, toString: 1, fret: 1, text: "1" }] },
	"A#m": { fingers: [[4, 3], [3, 3], [2, 2]], barres: [{ fromString: 5, toString: 1, fret: 1, text: "1" }] },
	"A#7": { fingers: [[4, 3], [3, 1], [2, 3]], barres: [{ fromString: 5, toString: 1, fret: 1, text: "1" }] },
	"A#m7": { fingers: [[4, 3], [3, 1], [2, 2]], barres: [{ fromString: 5, toString: 1, fret: 1, text: "1" }] },
	"A#maj7": { fingers: [[4, 3], [3, 2], [2, 3]], barres: [{ fromString: 5, toString: 1, fret: 1, text: "1" }] },

	"B": { fingers: [[4, 4], [3, 4], [2, 4], [1, 2]], barres: [{ fromString: 5, toString: 1, fret: 2, text: "1" }] },
	"Bm": { fingers: [[4, 4], [3, 4], [2, 3], [1, 2]], barres: [{ fromString: 5, toString: 1, fret: 2, text: "1" }] },
	"B7": { fingers: [[5, 2], [4, 1], [3, 2], [1, 2]], barres: [] },
	"Bm7": { fingers: [[5, 2], [3, 2], [1, 2]], barres: [] },

	"C": { fingers: [[5, 3], [4, 2], [2, 1]], barres: [] },
	"Cm": { fingers: [[4, 5], [3, 5], [2, 4], [1, 3]], barres: [{ fromString: 5, toString: 1, fret: 3, text: "1" }] },
	"C7": { fingers: [[5, 3], [4, 2], [3, 3], [2, 1]], barres: [] },
	"Cmaj7": { fingers: [[5, 3], [4, 2]], barres: [] },
	"Csus2": { fingers: [[5, 3], [2, 1]], barres: [] },
	"Csus4": { fingers: [[5, 3], [4, 3], [2, 1]], barres: [] },
	"Cadd9": { fingers: [[5, 3], [4, 2], [2, 3], [1, 3]], barres: [] },
	"C6": { fingers: [[5, 3], [4, 2], [3, 2], [2, 1]], barres: [] },
	"Cdim": { fingers: [[5, 3], [4, 4], [3, 5], [2, 4]], barres: [] },
	"C5": { fingers: [[4, 5], [3, 5]], barres: [] },
	"C#": { fingers: [[4, 6], [3, 6], [2, 6]], barres: [{ fromString: 5, toString: 1, fret: 4, text: "1" }] },
	"C#m": { fingers: [[4, 6], [3, 6], [2, 5]], barres: [{ fromString: 5, toString: 1, fret: 4, text: "1" }] },
	"C#7": { fingers: [[4, 6], [3, 4], [2, 6]], barres: [{ fromString: 5, toString: 1, fret: 4, text: "1" }] },
	"C#m7": { fingers: [[4, 6], [3, 4], [2, 5]], barres: [{ fromString: 5, toString: 1, fret: 4, text: "1" }] },
	"C#maj7": { fingers: [[4, 6], [3, 5], [2, 6]], barres: [{ fromString: 5, toString: 1, fret: 4, text: "1" }] },

	"D": { fingers: [[3, 2], [2, 3], [1, 2]], barres: [] },
	"Dm": { fingers: [[3, 2], [2, 3], [1, 1]], barres: [] },
	"D7": { fingers: [[3, 2], [2, 1], [1, 2]], barres: [] },
	"Dm7": { fingers: [[3, 2], [2, 1], [1, 1]], barres: [] },
	"Dmaj7": { fingers: [[3, 2], [2, 2], [1, 2]], barres: [] },
	"Dsus2": { fingers: [[3, 2], [2, 3]], barres: [] },
	"Dsus4": { fingers: [[3, 2], [2, 3], [1, 3]], barres: [] },
	"D6": { fingers: [[3, 2], [1, 2]], barres: [] },
	"D5": { fingers: [[3, 2], [2, 3]], barres: [] },
	"D#": { fingers: [[4, 8], [3, 8], [2, 8]], barres: [{ fromString: 5, toString: 1, fret: 6, text: "1" }] },
	"D#m": { fingers: [[4, 8], [3, 8], [2, 7]], barres: [{ fromString: 5, toString: 1, fret: 6, text: "1" }] },
	"D#7": { fingers: [[4, 8], [3, 6], [2, 8]], barres: [{ fromString: 5, toString: 1, fret: 6, text: "1" }] },
	"D#m7": { fingers: [[4, 8], [3, 6], [2, 7]], barres: [{ fromString: 5, toString: 1, fret: 6, text: "1" }] },
	"D#maj7": { fingers: [[4, 8], [3, 7], [2, 8]], barres: [{ fromString: 5, toString: 1, fret: 6, text: "1" }] },

	"E": { fingers: [[5, 2], [4, 2], [3, 1]], barres: [] },
	"Em": { fingers: [[5, 2], [4, 2]], barres: [] },
	"E7": { fingers: [[5, 2], [3, 1]], barres: [] },
	"Em7": { fingers: [[5, 2]], barres: [] },
	"Emaj7": { fingers: [[5, 2], [4, 1], [3, 1]], barres: [] },
	"Esus4": { fingers: [[5, 2], [4, 2], [3, 2]], barres: [] },
	"E5": { fingers: [[5, 2], [4, 2]], barres: [] },

	"F": { fingers: [[5, 3], [4, 3], [3, 2]], barres: [{ fromString: 6, toString: 1, fret: 1, text: "1" }] },
	"Fm": { fingers: [[5, 3], [4, 3], [3, 1]], barres: [{ fromString: 6, toString: 1, fret: 1, text: "1" }] },
	"F7": { fingers: [[5, 3], [3, 2]], barres: [{ fromString: 6, toString: 1, fret: 1, text: "1" }] },
	"Fmaj7": { fingers: [[5, 3], [4, 2], [3, 2]], barres: [{ fromString: 6, toString: 1, fret: 1, text: "1" }] },
	"F#": { fingers: [[5, 4], [4, 4], [3, 3]], barres: [{ fromString: 6, toString: 1, fret: 2, text: "1" }] },
	"F#m": { fingers: [[5, 4], [4, 4]], barres: [{ fromString: 6, toString: 1, fret: 2, text: "1" }] },
	"F#7": { fingers: [[5, 4], [3, 3]], barres: [{ fromString: 6, toString: 1, fret: 2, text: "1" }] },
	"F#m7": { fingers: [[5, 4]], barres: [{ fromString: 6, toString: 1, fret: 2, text: "1" }] },
	"F#maj7": { fingers: [[5, 4], [4, 3], [3, 3]], barres: [{ fromString: 6, toString: 1, fret: 2, text: "1" }] },

	"G": { fingers: [[6, 3], [5, 2], [1, 3]], barres: [] },
	"Gm": { fingers: [[5, 5], [4, 5], [3, 4], [2, 3], [1, 3]], barres: [{ fromString: 6, toString: 1, fret: 3, text: "1" }] },
	"G7": { fingers: [[6, 3], [5, 2], [1, 1]], barres: [] },
	"Gmaj7": { fingers: [[6, 3], [5, 2], [1, 2]], barres: [] },
	"Gsus2": { fingers: [[6, 3], [3, 2], [2, 3], [1, 3]], barres: [] },
	"Gsus4": { fingers: [[6, 3], [5, 3], [2, 1], [1, 3]], barres: [] },
	"G6": { fingers: [[6, 3], [5, 2]], barres: [] },
	"G5": { fingers: [[5, 5], [4, 5]], barres: [] },
	"G#": { fingers: [[5, 6], [4, 6], [3, 5]], barres: [{ fromString: 6, toString: 1, fret: 4, text: "1" }] },
	"G#m": { fingers: [[5, 6], [4, 6]], barres: [{ fromString: 6, toString: 1, fret: 4, text: "1" }] },
	"G#7": { fingers: [[5, 6], [3, 5]], barres: [{ fromString: 6, toString: 1, fret: 4, text: "1" }] },
	"G#m7": { fingers: [[5, 6]], barres: [{ fromString: 6, toString: 1, fret: 4, text: "1" }] },
	"G#maj7": { fingers: [[5, 6], [4, 5], [3, 5]], barres: [{ fromString: 6, toString: 1, fret: 4, text: "1" }] },
};

export const acordeClasico = (nombre) => acordesGuitarra[nombre] ?? null;